"""Tests for InitFilePatcher."""

from pathlib import Path

from pbreflect.pbgen.patchers.init_file_patcher import InitFilePatcher


class TestInitFilePatcher:
    """Tests for InitFilePatcher.patch."""

    def test_adds_init_to_all_dirs(self, tmp_path: Path) -> None:
        code_dir = tmp_path / "clients"
        sub_dir = code_dir / "api"
        sub_dir.mkdir(parents=True)

        patcher = InitFilePatcher(str(code_dir))
        patcher.patch()

        assert (code_dir / "__init__.py").exists()
        assert (sub_dir / "__init__.py").exists()

    def test_does_not_overwrite_existing_init(self, tmp_path: Path) -> None:
        code_dir = tmp_path / "clients"
        code_dir.mkdir(parents=True)
        init_file = code_dir / "__init__.py"
        init_file.write_text("# custom init\n")

        patcher = InitFilePatcher(str(code_dir))
        patcher.patch()

        assert init_file.read_text() == "# custom init\n"

    def test_init_file_has_generated_comment(self, tmp_path: Path) -> None:
        code_dir = tmp_path / "clients"
        code_dir.mkdir(parents=True)

        patcher = InitFilePatcher(str(code_dir))
        patcher.patch()

        content = (code_dir / "__init__.py").read_text()
        assert "Generated by PBReflect" in content
