"""
Generated by pbreflect (https://github.com/ValeriyMenshikov/pbreflect).

Generated client code for  using pbreflect.

This module contains auto-generated gRPC client classes for the  package.
It provides strongly-typed sync gRPC clients that follow the "duck typing" principle.
"""

from typing import Iterable, Iterator

import grpc
from google.protobuf import empty_pb2

from example_clients.protos.account_pb2 import (
    ActivateAccountRequest,
    ActivateAccountResponse,
    ChangeAccountEmailRequest,
    ChangeAccountEmailResponse,
    ChangeAccountPasswordRequest,
    ChangeAccountPasswordResponse,
    GetAccountsByLoginRequest,
    GetAccountsByLoginResponse,
    GetAccountsRequest,
    GetAccountsResponse,
    GetCurrentAccountRequest,
    GetCurrentAccountResponse,
    LoginRequest,
    LoginResponse,
    LogoutAllRequest,
    LogoutRequest,
    RegisterAccountClientStreamResponse,
    RegisterAccountRequest,
    RegisterAccountResponse,
    ResetAccountPasswordRequest,
    ResetAccountPasswordResponse,
    UpdateAccountRequest,
    UpdateAccountResponse,
    User,
)


class _AccountServiceStub:
    """Internal stub class for AccountService service.

    This class provides direct access to the gRPC methods exposed by the service.
    It should not be used directly, but through the AccountServiceClient class.
    """

    def __init__(self, channel: grpc.Channel) -> None:
        """Initialize the stub with a gRPC channel.

        Args:
            channel: gRPC channel for communication
        """
        self.Login = channel.unary_unary(
            "/AccountService/Login",
            request_serializer=LoginRequest.SerializeToString,
            response_deserializer=LoginResponse.FromString,
        )
        self.Logout = channel.unary_unary(
            "/AccountService/Logout",
            request_serializer=LogoutRequest.SerializeToString,
            response_deserializer=empty_pb2.Empty.FromString,
        )
        self.LogoutAll = channel.unary_unary(
            "/AccountService/LogoutAll",
            request_serializer=LogoutAllRequest.SerializeToString,
            response_deserializer=empty_pb2.Empty.FromString,
        )
        self.GetCurrentAccount = channel.unary_unary(
            "/AccountService/GetCurrentAccount",
            request_serializer=GetCurrentAccountRequest.SerializeToString,
            response_deserializer=GetCurrentAccountResponse.FromString,
        )
        self.GetAccounts = channel.unary_unary(
            "/AccountService/GetAccounts",
            request_serializer=GetAccountsRequest.SerializeToString,
            response_deserializer=GetAccountsResponse.FromString,
        )
        self.RegisterAccount = channel.unary_unary(
            "/AccountService/RegisterAccount",
            request_serializer=RegisterAccountRequest.SerializeToString,
            response_deserializer=RegisterAccountResponse.FromString,
        )
        self.ActivateAccount = channel.unary_unary(
            "/AccountService/ActivateAccount",
            request_serializer=ActivateAccountRequest.SerializeToString,
            response_deserializer=ActivateAccountResponse.FromString,
        )
        self.ChangeAccountEmail = channel.unary_unary(
            "/AccountService/ChangeAccountEmail",
            request_serializer=ChangeAccountEmailRequest.SerializeToString,
            response_deserializer=ChangeAccountEmailResponse.FromString,
        )
        self.ResetAccountPassword = channel.unary_unary(
            "/AccountService/ResetAccountPassword",
            request_serializer=ResetAccountPasswordRequest.SerializeToString,
            response_deserializer=ResetAccountPasswordResponse.FromString,
        )
        self.ChangeAccountPassword = channel.unary_unary(
            "/AccountService/ChangeAccountPassword",
            request_serializer=ChangeAccountPasswordRequest.SerializeToString,
            response_deserializer=ChangeAccountPasswordResponse.FromString,
        )
        self.UpdateAccount = channel.unary_unary(
            "/AccountService/UpdateAccount",
            request_serializer=UpdateAccountRequest.SerializeToString,
            response_deserializer=UpdateAccountResponse.FromString,
        )
        self.RegisterAccountClientStream = channel.stream_unary(
            "/AccountService/RegisterAccountClientStream",
            request_serializer=RegisterAccountRequest.SerializeToString,
            response_deserializer=RegisterAccountClientStreamResponse.FromString,
        )
        self.GetAccountsServerStream = channel.unary_stream(
            "/AccountService/GetAccountsServerStream",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=User.FromString,
        )
        self.GetAccountsByLoginDuplexStream = channel.stream_stream(
            "/AccountService/GetAccountsByLoginDuplexStream",
            request_serializer=GetAccountsByLoginRequest.SerializeToString,
            response_deserializer=GetAccountsByLoginResponse.FromString,
        )


class AccountServiceClient:
    """Client for the AccountService service.

    This class provides a strongly-typed sync interface to the gRPC service.
    """

    def __init__(self, channel: grpc.Channel) -> None:
        """Initialize the client with a gRPC channel.

        Args:
            channel: gRPC channel for communication
        """
        self._stub = _AccountServiceStub(channel)

    def login(
        self,
        request: LoginRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> LoginResponse:
        call = self._stub.Login(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def logout(
        self,
        request: LogoutRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> empty_pb2.Empty:
        call = self._stub.Logout(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def logout_all(
        self,
        request: LogoutAllRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> empty_pb2.Empty:
        call = self._stub.LogoutAll(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def get_current_account(
        self,
        request: GetCurrentAccountRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> GetCurrentAccountResponse:
        call = self._stub.GetCurrentAccount(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def get_accounts(
        self,
        request: GetAccountsRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> GetAccountsResponse:
        call = self._stub.GetAccounts(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def register_account(
        self,
        request: RegisterAccountRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> RegisterAccountResponse:
        call = self._stub.RegisterAccount(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def activate_account(
        self,
        request: ActivateAccountRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> ActivateAccountResponse:
        call = self._stub.ActivateAccount(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def change_account_email(
        self,
        request: ChangeAccountEmailRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> ChangeAccountEmailResponse:
        call = self._stub.ChangeAccountEmail(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def reset_account_password(
        self,
        request: ResetAccountPasswordRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> ResetAccountPasswordResponse:
        call = self._stub.ResetAccountPassword(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def change_account_password(
        self,
        request: ChangeAccountPasswordRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> ChangeAccountPasswordResponse:
        call = self._stub.ChangeAccountPassword(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def update_account(
        self,
        request: UpdateAccountRequest,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> UpdateAccountResponse:
        call = self._stub.UpdateAccount(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def register_account_client_stream(
        self,
        request_iterator: Iterator[RegisterAccountRequest],
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> RegisterAccountClientStreamResponse:
        call = self._stub.RegisterAccountClientStream(
            request_iterator,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def get_accounts_server_stream(
        self,
        request: empty_pb2.Empty,
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> Iterable[User]:
        call = self._stub.GetAccountsServerStream(
            request,
            metadata=metadata,
            timeout=timeout,
        )
        return call

    def get_accounts_by_login_duplex_stream(
        self,
        request_iterator: Iterator[GetAccountsByLoginRequest],
        metadata: list[tuple[str, str]] | None = None,
        timeout: float | None = None,
    ) -> Iterable[GetAccountsByLoginResponse]:
        call = self._stub.GetAccountsByLoginDuplexStream(
            request_iterator,
            metadata=metadata,
            timeout=timeout,
        )
        return call
