"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import sys

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
from builtins import (
    bool,
    int,
    str,
    type,
)
from collections.abc import (
    Iterable,
)
from google.protobuf.descriptor import (
    Descriptor,
    EnumDescriptor,
    FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer,
)
from google.protobuf.internal.enum_type_wrapper import (
    EnumTypeWrapper,
)
from google.protobuf.message import (
    Message,
)
from google.protobuf.timestamp_pb2 import (
    Timestamp,
)
from google.protobuf.wrappers_pb2 import (
    BoolValue,
    Int32Value,
    StringValue,
)
from typing import (
    Literal,
    NewType,
    final,
    overload,
)

DESCRIPTOR: FileDescriptor


_UserRole: _UserRole

class _UserRole:
    ValueType = NewType("ValueType", int)
    V: typing_extensions.TypeAlias = ValueType


_UserRoleEnumTypeWrapper: _UserRoleEnumTypeWrapper

class _UserRoleEnumTypeWrapper(EnumTypeWrapper[_UserRole.ValueType], type):
    DESCRIPTOR: EnumDescriptor
    Guest: _UserRole.ValueType  # 0
    Player: _UserRole.ValueType  # 1
    Administrator: _UserRole.ValueType  # 2
    NannyModerator: _UserRole.ValueType  # 3
    RegularModerator: _UserRole.ValueType  # 4
    SeniorModerator: _UserRole.ValueType  # 5


UserRole: UserRole

class UserRole(_UserRole, metaclass=_UserRoleEnumTypeWrapper): ...

Guest: UserRole.ValueType  # 0
Player: UserRole.ValueType  # 1
Administrator: UserRole.ValueType  # 2
NannyModerator: UserRole.ValueType  # 3
RegularModerator: UserRole.ValueType  # 4
SeniorModerator: UserRole.ValueType  # 5


_ColorSchema: _ColorSchema

class _ColorSchema:
    ValueType = NewType("ValueType", int)
    V: typing_extensions.TypeAlias = ValueType


_ColorSchemaEnumTypeWrapper: _ColorSchemaEnumTypeWrapper

class _ColorSchemaEnumTypeWrapper(EnumTypeWrapper[_ColorSchema.ValueType], type):
    DESCRIPTOR: EnumDescriptor
    Modern: _ColorSchema.ValueType  # 0
    Pale: _ColorSchema.ValueType  # 1
    Classic: _ColorSchema.ValueType  # 2
    ClassicPale: _ColorSchema.ValueType  # 3
    Night: _ColorSchema.ValueType  # 4


ColorSchema: ColorSchema

class ColorSchema(_ColorSchema, metaclass=_ColorSchemaEnumTypeWrapper): ...

Modern: ColorSchema.ValueType  # 0
Pale: ColorSchema.ValueType  # 1
Classic: ColorSchema.ValueType  # 2
ClassicPale: ColorSchema.ValueType  # 3
Night: ColorSchema.ValueType  # 4


_AccessPolicy: _AccessPolicy

class _AccessPolicy:
    ValueType = NewType("ValueType", int)
    V: typing_extensions.TypeAlias = ValueType


_AccessPolicyEnumTypeWrapper: _AccessPolicyEnumTypeWrapper

class _AccessPolicyEnumTypeWrapper(EnumTypeWrapper[_AccessPolicy.ValueType], type):
    DESCRIPTOR: EnumDescriptor
    NotSpecified: _AccessPolicy.ValueType  # 0
    DemocraticBan: _AccessPolicy.ValueType  # 1
    FullBan: _AccessPolicy.ValueType  # 2
    ChatBan: _AccessPolicy.ValueType  # 3
    RestrictContentEditing: _AccessPolicy.ValueType  # 4


AccessPolicy: AccessPolicy

class AccessPolicy(_AccessPolicy, metaclass=_AccessPolicyEnumTypeWrapper): ...

NotSpecified: AccessPolicy.ValueType  # 0
DemocraticBan: AccessPolicy.ValueType  # 1
FullBan: AccessPolicy.ValueType  # 2
ChatBan: AccessPolicy.ValueType  # 3
RestrictContentEditing: AccessPolicy.ValueType  # 4


LoginRequest: LoginRequest

class LoginRequest(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    PASSWORD_FIELD_NUMBER: int
    REMEMBER_ME_FIELD_NUMBER: int
    login: str
    password: str
    remember_me: bool
    def __init__(
        self,
        *,
        login: str | None = ...,
        password: str | None = ...,
        remember_me: bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_login", b"_login", "_password", b"_password", "_remember_me", b"_remember_me", "login", b"login", "password", b"password", "remember_me", b"remember_me"]) -> bool: ...
    def ClearField(self, field_name: Literal["_login", b"_login", "_password", b"_password", "_remember_me", b"_remember_me", "login", b"login", "password", b"password", "remember_me", b"remember_me"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_password", b"_password"]) -> Literal["password"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_remember_me", b"_remember_me"]) -> Literal["remember_me"] | None: ...


LoginResponse: LoginResponse

class LoginResponse(Message):
    DESCRIPTOR: Descriptor

    USER_FIELD_NUMBER: int
    TOKEN_FIELD_NUMBER: int
    token: str
    @property
    def user(self) -> UserEnvelope: ...
    def __init__(
        self,
        *,
        user: UserEnvelope | None = ...,
        token: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_token", b"_token", "_user", b"_user", "token", b"token", "user", b"user"]) -> bool: ...
    def ClearField(self, field_name: Literal["_token", b"_token", "_user", b"_user", "token", b"token", "user", b"user"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_token", b"_token"]) -> Literal["token"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_user", b"_user"]) -> Literal["user"] | None: ...


LogoutRequest: LogoutRequest

class LogoutRequest(Message):
    DESCRIPTOR: Descriptor

    TOKEN_FIELD_NUMBER: int
    token: str
    def __init__(
        self,
        *,
        token: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_token", b"_token", "token", b"token"]) -> bool: ...
    def ClearField(self, field_name: Literal["_token", b"_token", "token", b"token"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_token", b"_token"]) -> Literal["token"] | None: ...


LogoutAllRequest: LogoutAllRequest

class LogoutAllRequest(Message):
    DESCRIPTOR: Descriptor

    TOKEN_FIELD_NUMBER: int
    token: str
    def __init__(
        self,
        *,
        token: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_token", b"_token", "token", b"token"]) -> bool: ...
    def ClearField(self, field_name: Literal["_token", b"_token", "token", b"token"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_token", b"_token"]) -> Literal["token"] | None: ...


GetCurrentAccountRequest: GetCurrentAccountRequest

class GetCurrentAccountRequest(Message):
    DESCRIPTOR: Descriptor

    TOKEN_FIELD_NUMBER: int
    token: str
    def __init__(
        self,
        *,
        token: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_token", b"_token", "token", b"token"]) -> bool: ...
    def ClearField(self, field_name: Literal["_token", b"_token", "token", b"token"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_token", b"_token"]) -> Literal["token"] | None: ...


GetCurrentAccountResponse: GetCurrentAccountResponse

class GetCurrentAccountResponse(Message):
    DESCRIPTOR: Descriptor

    USER_FIELD_NUMBER: int
    @property
    def user(self) -> UserDetailsEnvelope: ...
    def __init__(
        self,
        *,
        user: UserDetailsEnvelope | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> bool: ...
    def ClearField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_user", b"_user"]) -> Literal["user"] | None: ...


GetAccountsRequest: GetAccountsRequest

class GetAccountsRequest(Message):
    DESCRIPTOR: Descriptor

    WITH_INACTIVE_FIELD_NUMBER: int
    PAGING_FIELD_NUMBER: int
    with_inactive: bool
    @property
    def paging(self) -> PagingQuery: ...
    def __init__(
        self,
        *,
        with_inactive: bool | None = ...,
        paging: PagingQuery | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_paging", b"_paging", "_with_inactive", b"_with_inactive", "paging", b"paging", "with_inactive", b"with_inactive"]) -> bool: ...
    def ClearField(self, field_name: Literal["_paging", b"_paging", "_with_inactive", b"_with_inactive", "paging", b"paging", "with_inactive", b"with_inactive"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_paging", b"_paging"]) -> Literal["paging"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_with_inactive", b"_with_inactive"]) -> Literal["with_inactive"] | None: ...


GetAccountsResponse: GetAccountsResponse

class GetAccountsResponse(Message):
    DESCRIPTOR: Descriptor

    ACCOUNTS_FIELD_NUMBER: int
    PAGING_FIELD_NUMBER: int
    @property
    def accounts(self) -> RepeatedCompositeFieldContainer[User]: ...
    @property
    def paging(self) -> PagingResult: ...
    def __init__(
        self,
        *,
        accounts: Iterable[User] | None = ...,
        paging: PagingResult | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_paging", b"_paging", "paging", b"paging"]) -> bool: ...
    def ClearField(self, field_name: Literal["_paging", b"_paging", "accounts", b"accounts", "paging", b"paging"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_paging", b"_paging"]) -> Literal["paging"] | None: ...


RegisterAccountRequest: RegisterAccountRequest

class RegisterAccountRequest(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    EMAIL_FIELD_NUMBER: int
    PASSWORD_FIELD_NUMBER: int
    login: str
    email: str
    password: str
    def __init__(
        self,
        *,
        login: str | None = ...,
        email: str | None = ...,
        password: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_email", b"_email", "_login", b"_login", "_password", b"_password", "email", b"email", "login", b"login", "password", b"password"]) -> bool: ...
    def ClearField(self, field_name: Literal["_email", b"_email", "_login", b"_login", "_password", b"_password", "email", b"email", "login", b"login", "password", b"password"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_email", b"_email"]) -> Literal["email"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_password", b"_password"]) -> Literal["password"] | None: ...


RegisterAccountResponse: RegisterAccountResponse

class RegisterAccountResponse(Message):
    DESCRIPTOR: Descriptor

    ID_FIELD_NUMBER: int
    LOGIN_FIELD_NUMBER: int
    id: str
    login: str
    def __init__(
        self,
        *,
        id: str | None = ...,
        login: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_id", b"_id", "_login", b"_login", "id", b"id", "login", b"login"]) -> bool: ...
    def ClearField(self, field_name: Literal["_id", b"_id", "_login", b"_login", "id", b"id", "login", b"login"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_id", b"_id"]) -> Literal["id"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...


RegisterAccountClientStreamResponse: RegisterAccountClientStreamResponse

class RegisterAccountClientStreamResponse(Message):
    DESCRIPTOR: Descriptor

    class Result(Message):
        DESCRIPTOR: Descriptor

        LOGIN_FIELD_NUMBER: int
        ID_FIELD_NUMBER: int
        ERROR_FIELD_NUMBER: int
        login: str
        id: str
        error: str
        def __init__(
            self,
            *,
            login: str | None = ...,
            id: str = ...,
            error: str = ...,
        ) -> None: ...
        def HasField(self, field_name: Literal["_login", b"_login", "error", b"error", "id", b"id", "login", b"login", "result", b"result"]) -> bool: ...
        def ClearField(self, field_name: Literal["_login", b"_login", "error", b"error", "id", b"id", "login", b"login", "result", b"result"]) -> None: ...
        @overload
        def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...
        @overload
        def WhichOneof(self, oneof_group: Literal["result", b"result"]) -> Literal["id", "error"] | None: ...

    RESULTS_FIELD_NUMBER: int
    @property
    def results(self) -> RepeatedCompositeFieldContainer[RegisterAccountClientStreamResponse.Result]: ...
    def __init__(
        self,
        *,
        results: Iterable[RegisterAccountClientStreamResponse.Result] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: Literal["results", b"results"]) -> None: ...


ActivateAccountRequest: ActivateAccountRequest

class ActivateAccountRequest(Message):
    DESCRIPTOR: Descriptor

    ACTIVATION_TOKEN_FIELD_NUMBER: int
    activation_token: str
    def __init__(
        self,
        *,
        activation_token: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_activation_token", b"_activation_token", "activation_token", b"activation_token"]) -> bool: ...
    def ClearField(self, field_name: Literal["_activation_token", b"_activation_token", "activation_token", b"activation_token"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_activation_token", b"_activation_token"]) -> Literal["activation_token"] | None: ...


ActivateAccountResponse: ActivateAccountResponse

class ActivateAccountResponse(Message):
    DESCRIPTOR: Descriptor

    USER_FIELD_NUMBER: int
    @property
    def user(self) -> UserEnvelope: ...
    def __init__(
        self,
        *,
        user: UserEnvelope | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> bool: ...
    def ClearField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_user", b"_user"]) -> Literal["user"] | None: ...


ChangeAccountEmailRequest: ChangeAccountEmailRequest

class ChangeAccountEmailRequest(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    PASSWORD_FIELD_NUMBER: int
    EMAIL_FIELD_NUMBER: int
    login: str
    password: str
    email: str
    def __init__(
        self,
        *,
        login: str | None = ...,
        password: str | None = ...,
        email: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_email", b"_email", "_login", b"_login", "_password", b"_password", "email", b"email", "login", b"login", "password", b"password"]) -> bool: ...
    def ClearField(self, field_name: Literal["_email", b"_email", "_login", b"_login", "_password", b"_password", "email", b"email", "login", b"login", "password", b"password"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_email", b"_email"]) -> Literal["email"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_password", b"_password"]) -> Literal["password"] | None: ...


ChangeAccountEmailResponse: ChangeAccountEmailResponse

class ChangeAccountEmailResponse(Message):
    DESCRIPTOR: Descriptor

    USER_FIELD_NUMBER: int
    @property
    def user(self) -> UserEnvelope: ...
    def __init__(
        self,
        *,
        user: UserEnvelope | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> bool: ...
    def ClearField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_user", b"_user"]) -> Literal["user"] | None: ...


ResetAccountPasswordRequest: ResetAccountPasswordRequest

class ResetAccountPasswordRequest(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    EMAIL_FIELD_NUMBER: int
    login: str
    email: str
    def __init__(
        self,
        *,
        login: str | None = ...,
        email: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_email", b"_email", "_login", b"_login", "email", b"email", "login", b"login"]) -> bool: ...
    def ClearField(self, field_name: Literal["_email", b"_email", "_login", b"_login", "email", b"email", "login", b"login"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_email", b"_email"]) -> Literal["email"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...


ResetAccountPasswordResponse: ResetAccountPasswordResponse

class ResetAccountPasswordResponse(Message):
    DESCRIPTOR: Descriptor

    USER_FIELD_NUMBER: int
    @property
    def user(self) -> UserEnvelope: ...
    def __init__(
        self,
        *,
        user: UserEnvelope | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> bool: ...
    def ClearField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_user", b"_user"]) -> Literal["user"] | None: ...


ChangeAccountPasswordRequest: ChangeAccountPasswordRequest

class ChangeAccountPasswordRequest(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    TOKEN_FIELD_NUMBER: int
    OLD_PASSWORD_FIELD_NUMBER: int
    NEW_PASSWORD_FIELD_NUMBER: int
    login: str
    old_password: str
    new_password: str
    @property
    def token(self) -> StringValue: ...
    def __init__(
        self,
        *,
        login: str | None = ...,
        token: StringValue | None = ...,
        old_password: str | None = ...,
        new_password: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_login", b"_login", "_new_password", b"_new_password", "_old_password", b"_old_password", "_token", b"_token", "login", b"login", "new_password", b"new_password", "old_password", b"old_password", "token", b"token"]) -> bool: ...
    def ClearField(self, field_name: Literal["_login", b"_login", "_new_password", b"_new_password", "_old_password", b"_old_password", "_token", b"_token", "login", b"login", "new_password", b"new_password", "old_password", b"old_password", "token", b"token"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_new_password", b"_new_password"]) -> Literal["new_password"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_old_password", b"_old_password"]) -> Literal["old_password"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_token", b"_token"]) -> Literal["token"] | None: ...


ChangeAccountPasswordResponse: ChangeAccountPasswordResponse

class ChangeAccountPasswordResponse(Message):
    DESCRIPTOR: Descriptor

    USER_FIELD_NUMBER: int
    @property
    def user(self) -> UserEnvelope: ...
    def __init__(
        self,
        *,
        user: UserEnvelope | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> bool: ...
    def ClearField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_user", b"_user"]) -> Literal["user"] | None: ...


UpdateAccountRequest: UpdateAccountRequest

class UpdateAccountRequest(Message):
    DESCRIPTOR: Descriptor

    TOKEN_FIELD_NUMBER: int
    USER_DATA_FIELD_NUMBER: int
    token: str
    @property
    def user_data(self) -> UserUpdate: ...
    def __init__(
        self,
        *,
        token: str | None = ...,
        user_data: UserUpdate | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_token", b"_token", "_user_data", b"_user_data", "token", b"token", "user_data", b"user_data"]) -> bool: ...
    def ClearField(self, field_name: Literal["_token", b"_token", "_user_data", b"_user_data", "token", b"token", "user_data", b"user_data"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_token", b"_token"]) -> Literal["token"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_user_data", b"_user_data"]) -> Literal["user_data"] | None: ...


UpdateAccountResponse: UpdateAccountResponse

class UpdateAccountResponse(Message):
    DESCRIPTOR: Descriptor

    USER_FIELD_NUMBER: int
    @property
    def user(self) -> UserDetailsEnvelope: ...
    def __init__(
        self,
        *,
        user: UserDetailsEnvelope | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> bool: ...
    def ClearField(self, field_name: Literal["_user", b"_user", "user", b"user"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_user", b"_user"]) -> Literal["user"] | None: ...


TimestampValue: TimestampValue

class TimestampValue(Message):
    DESCRIPTOR: Descriptor

    VALUE_FIELD_NUMBER: int
    @property
    def value(self) -> Timestamp: ...
    def __init__(
        self,
        *,
        value: Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_value", b"_value", "value", b"value"]) -> bool: ...
    def ClearField(self, field_name: Literal["_value", b"_value", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_value", b"_value"]) -> Literal["value"] | None: ...


UserRating: UserRating

class UserRating(Message):
    DESCRIPTOR: Descriptor

    ENABLED_FIELD_NUMBER: int
    QUALITY_FIELD_NUMBER: int
    QUANTITY_FIELD_NUMBER: int
    enabled: bool
    quality: int
    quantity: int
    def __init__(
        self,
        *,
        enabled: bool | None = ...,
        quality: int | None = ...,
        quantity: int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_enabled", b"_enabled", "_quality", b"_quality", "_quantity", b"_quantity", "enabled", b"enabled", "quality", b"quality", "quantity", b"quantity"]) -> bool: ...
    def ClearField(self, field_name: Literal["_enabled", b"_enabled", "_quality", b"_quality", "_quantity", b"_quantity", "enabled", b"enabled", "quality", b"quality", "quantity", b"quantity"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_enabled", b"_enabled"]) -> Literal["enabled"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_quality", b"_quality"]) -> Literal["quality"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_quantity", b"_quantity"]) -> Literal["quantity"] | None: ...


User: User

class User(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    ROLES_FIELD_NUMBER: int
    MEDIUM_PICTURE_URL_FIELD_NUMBER: int
    SMALL_PICTURE_URL_FIELD_NUMBER: int
    STATUS_FIELD_NUMBER: int
    RATING_FIELD_NUMBER: int
    ONLINE_FIELD_NUMBER: int
    NAME_FIELD_NUMBER: int
    LOCATION_FIELD_NUMBER: int
    REGISTRATION_FIELD_NUMBER: int
    login: str
    @property
    def roles(self) -> RepeatedScalarFieldContainer[UserRole.ValueType]: ...
    @property
    def medium_picture_url(self) -> StringValue: ...
    @property
    def small_picture_url(self) -> StringValue: ...
    @property
    def status(self) -> StringValue: ...
    @property
    def rating(self) -> UserRating: ...
    @property
    def online(self) -> TimestampValue: ...
    @property
    def name(self) -> StringValue: ...
    @property
    def location(self) -> StringValue: ...
    @property
    def registration(self) -> TimestampValue: ...
    def __init__(
        self,
        *,
        login: str | None = ...,
        roles: Iterable[UserRole.ValueType] | None = ...,
        medium_picture_url: StringValue | None = ...,
        small_picture_url: StringValue | None = ...,
        status: StringValue | None = ...,
        rating: UserRating | None = ...,
        online: TimestampValue | None = ...,
        name: StringValue | None = ...,
        location: StringValue | None = ...,
        registration: TimestampValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_location", b"_location", "_login", b"_login", "_medium_picture_url", b"_medium_picture_url", "_name", b"_name", "_online", b"_online", "_rating", b"_rating", "_registration", b"_registration", "_small_picture_url", b"_small_picture_url", "_status", b"_status", "location", b"location", "login", b"login", "medium_picture_url", b"medium_picture_url", "name", b"name", "online", b"online", "rating", b"rating", "registration", b"registration", "small_picture_url", b"small_picture_url", "status", b"status"]) -> bool: ...
    def ClearField(self, field_name: Literal["_location", b"_location", "_login", b"_login", "_medium_picture_url", b"_medium_picture_url", "_name", b"_name", "_online", b"_online", "_rating", b"_rating", "_registration", b"_registration", "_small_picture_url", b"_small_picture_url", "_status", b"_status", "location", b"location", "login", b"login", "medium_picture_url", b"medium_picture_url", "name", b"name", "online", b"online", "rating", b"rating", "registration", b"registration", "roles", b"roles", "small_picture_url", b"small_picture_url", "status", b"status"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_location", b"_location"]) -> Literal["location"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_medium_picture_url", b"_medium_picture_url"]) -> Literal["medium_picture_url"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_name", b"_name"]) -> Literal["name"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_online", b"_online"]) -> Literal["online"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_rating", b"_rating"]) -> Literal["rating"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_registration", b"_registration"]) -> Literal["registration"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_small_picture_url", b"_small_picture_url"]) -> Literal["small_picture_url"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_status", b"_status"]) -> Literal["status"] | None: ...


UserDetails: UserDetails

class UserDetails(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    ROLES_FIELD_NUMBER: int
    ORIGINAL_PICTURE_URL_FIELD_NUMBER: int
    MEDIUM_PICTURE_URL_FIELD_NUMBER: int
    SMALL_PICTURE_URL_FIELD_NUMBER: int
    STATUS_FIELD_NUMBER: int
    RATING_FIELD_NUMBER: int
    ONLINE_FIELD_NUMBER: int
    NAME_FIELD_NUMBER: int
    LOCATION_FIELD_NUMBER: int
    REGISTRATION_FIELD_NUMBER: int
    ICQ_FIELD_NUMBER: int
    SKYPE_FIELD_NUMBER: int
    INFO_FIELD_NUMBER: int
    login: str
    @property
    def roles(self) -> RepeatedScalarFieldContainer[UserRole.ValueType]: ...
    @property
    def original_picture_url(self) -> StringValue: ...
    @property
    def medium_picture_url(self) -> StringValue: ...
    @property
    def small_picture_url(self) -> StringValue: ...
    @property
    def status(self) -> StringValue: ...
    @property
    def rating(self) -> UserRating: ...
    @property
    def online(self) -> TimestampValue: ...
    @property
    def name(self) -> StringValue: ...
    @property
    def location(self) -> StringValue: ...
    @property
    def registration(self) -> TimestampValue: ...
    @property
    def icq(self) -> StringValue: ...
    @property
    def skype(self) -> StringValue: ...
    @property
    def info(self) -> StringValue: ...
    def __init__(
        self,
        *,
        login: str | None = ...,
        roles: Iterable[UserRole.ValueType] | None = ...,
        original_picture_url: StringValue | None = ...,
        medium_picture_url: StringValue | None = ...,
        small_picture_url: StringValue | None = ...,
        status: StringValue | None = ...,
        rating: UserRating | None = ...,
        online: TimestampValue | None = ...,
        name: StringValue | None = ...,
        location: StringValue | None = ...,
        registration: TimestampValue | None = ...,
        icq: StringValue | None = ...,
        skype: StringValue | None = ...,
        info: StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_icq", b"_icq", "_info", b"_info", "_location", b"_location", "_login", b"_login", "_medium_picture_url", b"_medium_picture_url", "_name", b"_name", "_online", b"_online", "_original_picture_url", b"_original_picture_url", "_rating", b"_rating", "_registration", b"_registration", "_skype", b"_skype", "_small_picture_url", b"_small_picture_url", "_status", b"_status", "icq", b"icq", "info", b"info", "location", b"location", "login", b"login", "medium_picture_url", b"medium_picture_url", "name", b"name", "online", b"online", "original_picture_url", b"original_picture_url", "rating", b"rating", "registration", b"registration", "skype", b"skype", "small_picture_url", b"small_picture_url", "status", b"status"]) -> bool: ...
    def ClearField(self, field_name: Literal["_icq", b"_icq", "_info", b"_info", "_location", b"_location", "_login", b"_login", "_medium_picture_url", b"_medium_picture_url", "_name", b"_name", "_online", b"_online", "_original_picture_url", b"_original_picture_url", "_rating", b"_rating", "_registration", b"_registration", "_skype", b"_skype", "_small_picture_url", b"_small_picture_url", "_status", b"_status", "icq", b"icq", "info", b"info", "location", b"location", "login", b"login", "medium_picture_url", b"medium_picture_url", "name", b"name", "online", b"online", "original_picture_url", b"original_picture_url", "rating", b"rating", "registration", b"registration", "roles", b"roles", "skype", b"skype", "small_picture_url", b"small_picture_url", "status", b"status"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_icq", b"_icq"]) -> Literal["icq"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_info", b"_info"]) -> Literal["info"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_location", b"_location"]) -> Literal["location"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_medium_picture_url", b"_medium_picture_url"]) -> Literal["medium_picture_url"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_name", b"_name"]) -> Literal["name"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_online", b"_online"]) -> Literal["online"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_original_picture_url", b"_original_picture_url"]) -> Literal["original_picture_url"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_rating", b"_rating"]) -> Literal["rating"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_registration", b"_registration"]) -> Literal["registration"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_skype", b"_skype"]) -> Literal["skype"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_small_picture_url", b"_small_picture_url"]) -> Literal["small_picture_url"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_status", b"_status"]) -> Literal["status"] | None: ...


UserUpdate: UserUpdate

class UserUpdate(Message):
    DESCRIPTOR: Descriptor

    STATUS_FIELD_NUMBER: int
    RATING_DISABLED_FIELD_NUMBER: int
    NAME_FIELD_NUMBER: int
    LOCATION_FIELD_NUMBER: int
    ICQ_FIELD_NUMBER: int
    SKYPE_FIELD_NUMBER: int
    INFO_FIELD_NUMBER: int
    USER_SETTINGS_FIELD_NUMBER: int
    @property
    def status(self) -> StringValue: ...
    @property
    def rating_disabled(self) -> BoolValue: ...
    @property
    def name(self) -> StringValue: ...
    @property
    def location(self) -> StringValue: ...
    @property
    def icq(self) -> StringValue: ...
    @property
    def skype(self) -> StringValue: ...
    @property
    def info(self) -> StringValue: ...
    @property
    def user_settings(self) -> UserSettings: ...
    def __init__(
        self,
        *,
        status: StringValue | None = ...,
        rating_disabled: BoolValue | None = ...,
        name: StringValue | None = ...,
        location: StringValue | None = ...,
        icq: StringValue | None = ...,
        skype: StringValue | None = ...,
        info: StringValue | None = ...,
        user_settings: UserSettings | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_icq", b"_icq", "_info", b"_info", "_location", b"_location", "_name", b"_name", "_rating_disabled", b"_rating_disabled", "_skype", b"_skype", "_status", b"_status", "_user_settings", b"_user_settings", "icq", b"icq", "info", b"info", "location", b"location", "name", b"name", "rating_disabled", b"rating_disabled", "skype", b"skype", "status", b"status", "user_settings", b"user_settings"]) -> bool: ...
    def ClearField(self, field_name: Literal["_icq", b"_icq", "_info", b"_info", "_location", b"_location", "_name", b"_name", "_rating_disabled", b"_rating_disabled", "_skype", b"_skype", "_status", b"_status", "_user_settings", b"_user_settings", "icq", b"icq", "info", b"info", "location", b"location", "name", b"name", "rating_disabled", b"rating_disabled", "skype", b"skype", "status", b"status", "user_settings", b"user_settings"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_icq", b"_icq"]) -> Literal["icq"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_info", b"_info"]) -> Literal["info"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_location", b"_location"]) -> Literal["location"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_name", b"_name"]) -> Literal["name"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_rating_disabled", b"_rating_disabled"]) -> Literal["rating_disabled"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_skype", b"_skype"]) -> Literal["skype"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_status", b"_status"]) -> Literal["status"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_user_settings", b"_user_settings"]) -> Literal["user_settings"] | None: ...


UserSettings: UserSettings

class UserSettings(Message):
    DESCRIPTOR: Descriptor

    COLOR_SCHEMA_FIELD_NUMBER: int
    NANNY_GREETINGS_MESSAGE_FIELD_NUMBER: int
    PAGING_SETTINGS_FIELD_NUMBER: int
    color_schema: ColorSchema.ValueType
    nanny_greetings_message: str
    @property
    def paging_settings(self) -> PagingSettings: ...
    def __init__(
        self,
        *,
        color_schema: ColorSchema.ValueType | None = ...,
        nanny_greetings_message: str | None = ...,
        paging_settings: PagingSettings | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_color_schema", b"_color_schema", "_nanny_greetings_message", b"_nanny_greetings_message", "_paging_settings", b"_paging_settings", "color_schema", b"color_schema", "nanny_greetings_message", b"nanny_greetings_message", "paging_settings", b"paging_settings"]) -> bool: ...
    def ClearField(self, field_name: Literal["_color_schema", b"_color_schema", "_nanny_greetings_message", b"_nanny_greetings_message", "_paging_settings", b"_paging_settings", "color_schema", b"color_schema", "nanny_greetings_message", b"nanny_greetings_message", "paging_settings", b"paging_settings"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_color_schema", b"_color_schema"]) -> Literal["color_schema"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_nanny_greetings_message", b"_nanny_greetings_message"]) -> Literal["nanny_greetings_message"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_paging_settings", b"_paging_settings"]) -> Literal["paging_settings"] | None: ...


PagingQuery: PagingQuery

class PagingQuery(Message):
    DESCRIPTOR: Descriptor

    SIZE_FIELD_NUMBER: int
    NUMBER_FIELD_NUMBER: int
    SKIP_FIELD_NUMBER: int
    @property
    def size(self) -> Int32Value: ...
    @property
    def number(self) -> Int32Value: ...
    @property
    def skip(self) -> Int32Value: ...
    def __init__(
        self,
        *,
        size: Int32Value | None = ...,
        number: Int32Value | None = ...,
        skip: Int32Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_number", b"_number", "_size", b"_size", "_skip", b"_skip", "number", b"number", "size", b"size", "skip", b"skip"]) -> bool: ...
    def ClearField(self, field_name: Literal["_number", b"_number", "_size", b"_size", "_skip", b"_skip", "number", b"number", "size", b"size", "skip", b"skip"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_number", b"_number"]) -> Literal["number"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_size", b"_size"]) -> Literal["size"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_skip", b"_skip"]) -> Literal["skip"] | None: ...


PagingResult: PagingResult

class PagingResult(Message):
    DESCRIPTOR: Descriptor

    TOTAL_PAGES_COUNT_FIELD_NUMBER: int
    TOTAL_ENTITIES_COUNT_FIELD_NUMBER: int
    CURRENT_PAGE_FIELD_NUMBER: int
    PAGE_SIZE_FIELD_NUMBER: int
    ENTITY_NUMBER_FIELD_NUMBER: int
    total_pages_count: int
    total_entities_count: int
    current_page: int
    page_size: int
    entity_number: int
    def __init__(
        self,
        *,
        total_pages_count: int | None = ...,
        total_entities_count: int | None = ...,
        current_page: int | None = ...,
        page_size: int | None = ...,
        entity_number: int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_current_page", b"_current_page", "_entity_number", b"_entity_number", "_page_size", b"_page_size", "_total_entities_count", b"_total_entities_count", "_total_pages_count", b"_total_pages_count", "current_page", b"current_page", "entity_number", b"entity_number", "page_size", b"page_size", "total_entities_count", b"total_entities_count", "total_pages_count", b"total_pages_count"]) -> bool: ...
    def ClearField(self, field_name: Literal["_current_page", b"_current_page", "_entity_number", b"_entity_number", "_page_size", b"_page_size", "_total_entities_count", b"_total_entities_count", "_total_pages_count", b"_total_pages_count", "current_page", b"current_page", "entity_number", b"entity_number", "page_size", b"page_size", "total_entities_count", b"total_entities_count", "total_pages_count", b"total_pages_count"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_current_page", b"_current_page"]) -> Literal["current_page"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_entity_number", b"_entity_number"]) -> Literal["entity_number"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_page_size", b"_page_size"]) -> Literal["page_size"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_total_entities_count", b"_total_entities_count"]) -> Literal["total_entities_count"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_total_pages_count", b"_total_pages_count"]) -> Literal["total_pages_count"] | None: ...


PagingSettings: PagingSettings

class PagingSettings(Message):
    DESCRIPTOR: Descriptor

    POSTS_PER_PAGE_FIELD_NUMBER: int
    COMMENTS_PER_PAGE_FIELD_NUMBER: int
    TOPICS_PER_PAGE_FIELD_NUMBER: int
    MESSAGES_PER_PAGE_FIELD_NUMBER: int
    ENTITIES_PER_PAGE_FIELD_NUMBER: int
    posts_per_page: int
    comments_per_page: int
    topics_per_page: int
    messages_per_page: int
    entities_per_page: int
    def __init__(
        self,
        *,
        posts_per_page: int | None = ...,
        comments_per_page: int | None = ...,
        topics_per_page: int | None = ...,
        messages_per_page: int | None = ...,
        entities_per_page: int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_comments_per_page", b"_comments_per_page", "_entities_per_page", b"_entities_per_page", "_messages_per_page", b"_messages_per_page", "_posts_per_page", b"_posts_per_page", "_topics_per_page", b"_topics_per_page", "comments_per_page", b"comments_per_page", "entities_per_page", b"entities_per_page", "messages_per_page", b"messages_per_page", "posts_per_page", b"posts_per_page", "topics_per_page", b"topics_per_page"]) -> bool: ...
    def ClearField(self, field_name: Literal["_comments_per_page", b"_comments_per_page", "_entities_per_page", b"_entities_per_page", "_messages_per_page", b"_messages_per_page", "_posts_per_page", b"_posts_per_page", "_topics_per_page", b"_topics_per_page", "comments_per_page", b"comments_per_page", "entities_per_page", b"entities_per_page", "messages_per_page", b"messages_per_page", "posts_per_page", b"posts_per_page", "topics_per_page", b"topics_per_page"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_comments_per_page", b"_comments_per_page"]) -> Literal["comments_per_page"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_entities_per_page", b"_entities_per_page"]) -> Literal["entities_per_page"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_messages_per_page", b"_messages_per_page"]) -> Literal["messages_per_page"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_posts_per_page", b"_posts_per_page"]) -> Literal["posts_per_page"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_topics_per_page", b"_topics_per_page"]) -> Literal["topics_per_page"] | None: ...


UserEnvelope: UserEnvelope

class UserEnvelope(Message):
    DESCRIPTOR: Descriptor

    RESOURCE_FIELD_NUMBER: int
    METADATA_FIELD_NUMBER: int
    @property
    def resource(self) -> User: ...
    @property
    def metadata(self) -> StringValue: ...
    def __init__(
        self,
        *,
        resource: User | None = ...,
        metadata: StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_metadata", b"_metadata", "_resource", b"_resource", "metadata", b"metadata", "resource", b"resource"]) -> bool: ...
    def ClearField(self, field_name: Literal["_metadata", b"_metadata", "_resource", b"_resource", "metadata", b"metadata", "resource", b"resource"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_metadata", b"_metadata"]) -> Literal["metadata"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_resource", b"_resource"]) -> Literal["resource"] | None: ...


UserDetailsEnvelope: UserDetailsEnvelope

class UserDetailsEnvelope(Message):
    DESCRIPTOR: Descriptor

    RESOURCE_FIELD_NUMBER: int
    METADATA_FIELD_NUMBER: int
    @property
    def resource(self) -> UserDetails: ...
    @property
    def metadata(self) -> StringValue: ...
    def __init__(
        self,
        *,
        resource: UserDetails | None = ...,
        metadata: StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_metadata", b"_metadata", "_resource", b"_resource", "metadata", b"metadata", "resource", b"resource"]) -> bool: ...
    def ClearField(self, field_name: Literal["_metadata", b"_metadata", "_resource", b"_resource", "metadata", b"metadata", "resource", b"resource"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_metadata", b"_metadata"]) -> Literal["metadata"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_resource", b"_resource"]) -> Literal["resource"] | None: ...


GetAccountsByLoginRequest: GetAccountsByLoginRequest

class GetAccountsByLoginRequest(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    login: str
    def __init__(
        self,
        *,
        login: str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_login", b"_login", "login", b"login"]) -> bool: ...
    def ClearField(self, field_name: Literal["_login", b"_login", "login", b"login"]) -> None: ...
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...


GetAccountsByLoginResponse: GetAccountsByLoginResponse

class GetAccountsByLoginResponse(Message):
    DESCRIPTOR: Descriptor

    LOGIN_FIELD_NUMBER: int
    USER_FIELD_NUMBER: int
    ERROR_FIELD_NUMBER: int
    login: str
    error: str
    @property
    def user(self) -> User: ...
    def __init__(
        self,
        *,
        login: str | None = ...,
        user: User | None = ...,
        error: str = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_login", b"_login", "error", b"error", "login", b"login", "result", b"result", "user", b"user"]) -> bool: ...
    def ClearField(self, field_name: Literal["_login", b"_login", "error", b"error", "login", b"login", "result", b"result", "user", b"user"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_login", b"_login"]) -> Literal["login"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["result", b"result"]) -> Literal["user", "error"] | None: ...
