"""Patcher for mypy .pyi stubs generated by protoc."""

from pathlib import Path


class MypyPatcher:
    """Fixes common issues in protoc-generated .pyi stub files."""

    def __init__(self, code_dir: str) -> None:
        self.code_dir = Path(code_dir)

    def patch(self) -> None:
        for stub in self.code_dir.rglob("*.pyi"):
            content = stub.read_text(encoding="utf-8", errors="ignore")
            content = self._remove_final_decorators(content)
            content = self._fix_class_names(content)
            content = self._add_class_annotations(content, stub)
            content = self._fix_imports(content)
            stub.write_text(content, encoding="utf-8")

    @staticmethod
    def _remove_final_decorators(content: str) -> str:
        return "".join(
            line
            for line in content.splitlines(keepends=True)
            if not (line.strip().startswith("@") and "final" in line.strip())
        )

    @staticmethod
    def _fix_class_names(content: str) -> str:
        return content.replace("_EnumTypeWrapper", "EnumTypeWrapper").replace(
            "_ExtensionFieldDescriptor", "ExtensionFieldDescriptor"
        )

    @staticmethod
    def _add_class_annotations(content: str, stub: Path) -> str:
        if "_pb2.pyi" not in stub.name:
            return content
        result = []
        for line in content.splitlines(keepends=True):
            if line.startswith("class "):
                class_name = line.split("class ")[1].split("(")[0].split(":")[0].strip()
                result.append(f"\n{class_name}: {class_name}\n\n")
            result.append(line)
        return "".join(result)

    def _fix_imports(self, content: str) -> str:
        output_dir_name = self.code_dir.name
        result = []
        for line in content.splitlines(keepends=True):
            if "from " in line and " import" in line:
                imp_str = line.split("from ")[1].split(" import")[0].strip()
                if not imp_str.startswith(("google.", "grpc.")) and not imp_str.startswith(f"{output_dir_name}."):
                    pb_path = self.code_dir / f"{imp_str.replace('.', '/')}.pyi"
                    if pb_path.exists():
                        line = line.replace(f"from {imp_str} import", f"from {output_dir_name}.{imp_str} import")
            result.append(line)
        return "".join(result)
